/*export const SET_BTC_EX_RATE = 'SET_BTC_EX_RATE';
export const SET_ETH_EX_RATE = 'SET_ETH_EX_RATE';
export const SET_XRP_EX_RATE = 'SET_XRP_EX_RATE';*/
export const SET_ALL_EX_RATES = 'SET_ALL_EX_RATES';
export const SET_ERROR = 'SET_ERROR';
export const SET_SELECTED_CRYPTO_WIDGET = 'SET_SELECTED_CRYPTO_WIDGET';
export const SET_SELECTED_NATIONAL_CURR = 'SET_SELECTED_NATIONAL_CURR';
export const SET_VOLUME = 'SET_VOLUME';
