export const SET_ALL_EX_RATES = 'SET_ALL_EX_RATES';
export const SET_ERROR = 'SET_ERROR';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_SELECTED_CRYPTO_WIDGET = 'SET_SELECTED_CRYPTO_WIDGET';
export const SET_SELECTED_NATIONAL_CURR = 'SET_SELECTED_NATIONAL_CURR';
export const SET_VOLUME = 'SET_VOLUME';
