export const GET_BTC_RATES_ASYNC = 'GET_BTC_RATES_ASYNC';
export const GET_ETH_RATES_ASYNC = 'GET_ETH_RATES_ASYNC';
export const GET_XRP_RATES_ASYNC = 'GET_XRP_RATES_ASYNC';
export const GET_ALL_RATES_ASYNC = 'GET_ALL_RATES_ASYNC';
